DECLARE @dbName VARCHAR(50) = 'TestingDB'
DECLARE @tblName VARCHAR(50)

SELECT @tblName = COUNT(TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG=@dbName


WHILE @tblName > 0
BEGIN

	EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT all'
	EXEC sp_msforeachtable 'DROP TABLE ?'

	SELECT @tblName = COUNT(TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG=@dbName

END